import { expect, test } from '@playwright/test';

test('first method cycle preserves the task and writes one review only after rating', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 700 });
  await page.goto('/');
  await page.evaluate(() => { document.documentElement.style.fontSize = '20px'; });
  const source = page.locator('.source-sentence');
  await expect(source).toHaveText('To jest moja piękna żona.');
  await expect(page.getByRole('button', { name: 'Перейти к заданию' })).toBeVisible();
  await expect(page.locator('.answer-sentence')).toHaveCount(0);
  const reference = page.getByRole('button', { name: 'Таблица под рукой' });
  await expect(reference).toBeDisabled();
  await expect(page.locator('.reference-panel')).toHaveCount(0);
  const method = page.getByRole('combobox', { name: 'Подача объяснений' });
  await method.selectOption('situations');
  await expect(page.locator('.method-introduce')).toContainText('кого или что видишь');
  await expect(source).toHaveText('To jest moja piękna żona.');
  await page.getByRole('button', { name: 'Перейти к заданию' }).click();
  await expect(reference).toBeEnabled();
  await page.getByRole('button', { name: 'Таблица под рукой' }).click();
  await expect(page.locator('.reference-panel')).toContainText('moją piękną żonę');
  await page.getByRole('button', { name: 'Скрыть таблицу' }).click();
  await expect(source).toHaveText('To jest moja piękna żona.');
  await page.getByRole('button', { name: 'Напечатать ответ' }).click();
  const answer = page.getByRole('textbox', { name: 'Ответ по-польски' });
  await answer.fill('Moja próba');
  await method.selectOption('logic');
  await expect(answer).toHaveValue('Moja próba');
  await page.getByRole('button', { name: /Проверить и показать ответ/ }).click();
  await expect(page.locator('.method-feedback h3')).toHaveText('Разбор изменений');
  await method.selectOption('situations');
  await expect(page.locator('.method-feedback h3')).toHaveText('Сравни смысл и форму');
  await expect(page.locator('.typed-result p')).toHaveText('Moja próba');
  expect(await page.evaluate(() => localStorage.getItem('polski-grammar-srs-v1'))).toBeNull();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);
  await page.getByRole('button', { name: 'Таблица под рукой' }).click();
  await page.getByRole('button', { name: /Вспомнил/ }).click();
  const progress = await page.evaluate(() => JSON.parse(localStorage.getItem('polski-grammar-srs-v1')!));
  expect(progress.totalReviews).toBe(1);
  await expect(page.getByRole('button', { name: 'Перейти к заданию' })).toBeVisible();
  await expect(page.locator('.reference-panel')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Таблица под рукой' })).toBeDisabled();
  await page.getByRole('button', { name: 'Перейти к заданию' }).click();
  await expect(page.locator('.reference-panel')).toBeVisible();
  await page.reload();
  await expect(page.getByRole('combobox', { name: 'Подача объяснений' })).toHaveValue('situations');
});
