import {useEffect,useMemo,useState} from 'react';import type {RatingName} from '../types';import {skills,skillById} from '../training/skills';import {generateForSkill} from '../training/generator';import {evaluate} from '../training/evaluator';import {isDue,preview,review} from '../srs/scheduler';import {exportProgress,freshProgress,loadProgress,saveProgress} from '../progress/storage';import {nextSkillId} from '../training/queue';import {localDay} from '../progress/storage';import './style.css';
const dueText=(d:Date)=>{const m=Math.max(1,Math.round((d.getTime()-Date.now())/60000));if(m<60)return`${m}m`;const h=Math.round(m/60);if(h<48)return`${h}h`;return`${Math.round(h/24)}d`};
export default function App(){
 const [progress,setProgress]=useState(loadProgress);const [selected,setSelected]=useState<string|null>(null);
 const [exercise,setExercise]=useState(()=>generateForSkill(nextSkillId(progress)));const [answer,setAnswer]=useState('');const [checked,setChecked]=useState(false);const [tab,setTab]=useState<'train'|'theory'|'progress'>('train');
 const [,tick]=useState(0);useEffect(()=>{const timer=setInterval(()=>tick(n=>n+1),30000);return()=>clearInterval(timer)},[]);
 const evaluation=useMemo(()=>evaluate(answer,exercise),[answer,exercise]);const skill=skillById(exercise.primarySkill);const sc=progress.cards.find(c=>c.skillId===exercise.primarySkill)!;const intervals=preview(sc);const dueCount=progress.cards.filter(isDue).length;
 const choose=(id:string)=>{setSelected(id);setExercise(generateForSkill(id));setAnswer('');setChecked(false);setTab('train')};
 const next=(p=progress,selection=selected)=>{setExercise(generateForSkill(nextSkillId(p,selection)));setAnswer('');setChecked(false)};
 const automatic=()=>{setSelected(null);next(progress,null);setTab('train')};
 function rate(r:RatingName){if(!checked)return;const cards=progress.cards.map(c=>c.skillId===exercise.primarySkill?review(c,r):c);const old=progress.stats[exercise.primarySkill];const ok=evaluation.correct;const np={...progress,cards,stats:{...progress.stats,[exercise.primarySkill]:{reviews:old.reviews+1,correct:old.correct+(ok?1:0),streak:ok?old.streak+1:0,mistakes:old.mistakes+(ok?0:1)}},reviewsToday:(progress.lastDay===localDay()?progress.reviewsToday:0)+1,lastDay:localDay(),totalReviews:progress.totalReviews+1};setProgress(np);saveProgress(np);next(np)}
 function reset(){if(confirm('Сбросить весь прогресс?')){const p=freshProgress();setProgress(p);saveProgress(p);setSelected(null);next(p,null)}}
 function download(){const blob=new Blob([exportProgress(progress)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='polski-srs-progress.json';a.click();URL.revokeObjectURL(a.href)}
 const groups=[...new Set(skills.map(s=>s.group))];
 return <div className="app"><header className="top"><div><h1>POLSKI <span>// Grammar SRS</span></h1><p>Правило → трансформация → интервальное повторение.</p></div><div className="topstats"><b>{dueCount}</b><span>due</span><b>{progress.reviewsToday}</b><span>today</span></div></header>
 <nav><button className={tab==='train'?'active':''} onClick={()=>setTab('train')}>Тренировка</button><button className={tab==='theory'?'active':''} onClick={()=>setTab('theory')}>Теория</button><button className={tab==='progress'?'active':''} onClick={()=>setTab('progress')}>Прогресс</button></nav>
 {tab==='train'&&<main className="layout"><aside className="sidebar"><button className={"skill "+(selected===null?"sel":"")} onClick={automatic}>По расписанию</button>{groups.map(g=><section key={g}><h3>{g}</h3>{skills.filter(s=>s.group===g).map(s=>{const st=progress.stats[s.id],acc=st.reviews?Math.round(st.correct/st.reviews*100):0;return <button key={s.id} onClick={()=>choose(s.id)} className={'skill '+(s.id===exercise.primarySkill?'sel':'')}><span><b>{s.title}</b><small>{s.level} · {st.reviews} reps</small></span><em>{acc}%</em></button>})}</section>)}</aside>
 <section className="trainer card">{selected===null&&dueCount===0?<><h2>Повторения на сейчас завершены</h2><p>Следующее повторение: {new Date(sc.card.due).toLocaleString('ru-RU')}.</p><p>Для дополнительной тренировки выбери навык слева.</p></>:<><div className="eyebrow">{skill.level} · {skill.group}</div><h2>{skill.title}</h2><div className="formula">{skill.formula}</div><div className="prompt">{exercise.prompt}</div><input aria-label="Ответ по-польски" autoFocus readOnly={checked} value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!checked)setChecked(true)}} placeholder="Напиши ответ по-польски…"/>{!checked?<button className="primary" onClick={()=>setChecked(true)}>Проверить</button>:<><div className={'result '+(evaluation.correct?'ok':'bad')}><strong>{evaluation.correct?'✓ Правильно':'✕ Есть ошибка'}</strong>{!evaluation.correct&&<><div className="your">Твой ответ: {answer||'—'}</div><div className="expected">✓ {exercise.expected}</div></>}<p>{exercise.explanation}</p></div><div className="ratings">{(['again','hard','good','easy'] as RatingName[]).map(r=><button key={r} onClick={()=>rate(r)}><b>{r}</b><small>{dueText(intervals[r])}</small></button>)}</div></>}</>}</section>
 <aside className="card help"><h3>Почему так</h3><p>{skill.theory}</p><h3>Подсказка</h3><p>{skill.hint}</p><div className="tags">{exercise.tags.map(t=><span key={t}>{t}</span>)}</div></aside></main>}
 {tab==='theory'&&<main className="theoryPage"><div className="card hero"><h2>Grammar Map — B1 Core</h2><p>Не учи 7 падежей как 7 независимых тем. Выбирай конструкцию → она требует падеж → весь noun phrase согласуется.</p><pre>{`КОНСТРУКЦИЯ → CASE → pronoun + adjective + noun\n\nwidzę → ACC\nnie mam → GEN\nz → INST\no → LOC\ndaję → DAT`}</pre></div><section className="card theoryGroup"><h2>Падежи — карта триггеров</h2><div className="cheat"><b>Mianownik</b><span>kto? co?</span><code>To jest moja żona.</code><b>Dopełniacz</b><span>kogo? czego?</span><code>nie mam / bez / do</code><b>Celownik</b><span>komu? czemu?</span><code>daję / pomagam</code><b>Biernik</b><span>kogo? co?</span><code>widzę / mam / lubię</code><b>Narzędnik</b><span>z kim? z czym?</span><code>z / jestem</code><b>Miejscownik</b><span>o kim? o czym?</span><code>o / w / na</code><b>Wołacz</b><span>обращение</span><code>Marku! Anno!</code></div></section><section className="card theoryGroup"><h2>Мужской Biernik — главный switch</h2><pre>{`m-personal:  widzę męża → ACC = GEN\nна -a:      widzę kolegę, но nie widzę kolegi\nm-animate:   widzę psa / kota       → ACC = GEN\nm-inanimate: widzę dom / samochód  → ACC = NOM`}</pre><h2>Отрицание</h2><pre>{`Mam nowy samochód.        [ACC]\nNie mam nowego samochodu. [GEN]`}</pre><h2>Времена</h2><pre>{`robię      → NOW\nrobiłem    → PAST\nbędę robić → FUTURE imperfective\nzrobię     → FUTURE perfective`}</pre></section>{groups.map(g=><section className="card theoryGroup" key={g}><h2>{g}</h2>{skills.filter(s=>s.group===g).map(s=><article key={s.id}><h3>{s.title} <small>{s.level}</small></h3><code>{s.formula}</code><p>{s.theory}</p></article>)}</section>)}</main>}
 {tab==='progress'&&<main className="progressPage"><section className="card summary"><h2>Прогресс</h2><div className="bigstats"><div><b>{progress.totalReviews}</b><span>всего повторений</span></div><div><b>{progress.reviewsToday}</b><span>сегодня</span></div><div><b>{dueCount}</b><span>сейчас due</span></div></div><div className="actions"><button onClick={download}>Экспорт JSON</button><button onClick={reset}>Сбросить</button></div></section><section className="card"><h2>Навыки</h2>{skills.map(s=>{const st=progress.stats[s.id],a=st.reviews?Math.round(st.correct/st.reviews*100):0;return <div className="row" key={s.id}><span>{s.title}</span><div className="bar"><i style={{width:`${a}%`}}/></div><b>{a}%</b><small>{st.reviews} reps · streak {st.streak}</small></div>})}</section></main>}
 <footer>Все данные хранятся локально в браузере. FSRS планирует интервалы; каждое повторение генерирует новую фразу.</footer></div>
}
