"""Regenerate the UC-07 byte-parity test against the LIVE ExerciseFactory.

UniversalCorePlan.md §5.3/§12 UC-07: "ExerciseGenerator работает параллельно старому
ExerciseFactory/GrammarEngine на одних и тех же (skillId, seed, seedRandom); сравнение —
побайтное." This generates exactly that: for every (skillId/seed, RNG draws) combination in
tests/fixtures/core-golden/exercises.json, it builds BOTH the old `ExerciseFactory` and the new
`ExerciseGenerator` from the same draws and asserts their outputs are identical `Exercise` values —
comparing live code to live code, never to a static literal. This is deliberately NOT a literal
transcription of core-golden's `expected` field: core-golden was found to be stale for
`case.gen.neg` (15/112 cases carry only 1 of the 2 FormChanges the live ExerciseFactory produces —
verified against TrainingParityTest, which IS current). Reproduce: for id, count in
[('C-01-03', ...)] compare `len(case['expected']['changes'])` against `FormChange(` occurrences in
TrainingParityTest.kt's matching block. Comparing to the live factory sidesteps that drift while
still exercising every (skillId × seed × draw) core-golden pins.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[7]
OUT = Path(__file__).with_name('UniversalCoreParityTest.kt')
FIXTURE = ROOT / 'tests/fixtures/core-golden/exercises.json'
ex = json.loads(FIXTURE.read_text())
assert ex['schemaVersion'] == 1
assert len(ex['cases']) == 112


def s(value):
    return json.dumps(value, ensure_ascii=False).replace('$', "\\$")


def seed_map(value):
    return 'mapOf("noun" to %s, "adjective" to %s)' % (s(value['nounId']), s(value['adjectiveId']))


def sentence_seed(value):
    return 'SentenceSeed(%s, %s)' % (s(value['nounId']), s(value['adjectiveId']))


lines = [
    'package polski.core',
    '',
    'import kotlin.test.Test',
    'import kotlin.test.assertEquals',
    'import polski.model.SentenceSeed',
    '',
    '/**',
    ' * Generated by generate_uc07_parity.py from tests/fixtures/core-golden/exercises.json\'s',
    ' * (skillId/seed, RNG draws) inputs — DO NOT EDIT BY HAND. UniversalCorePlan.md §5.3/§12 UC-07:',
    ' * compares the LIVE `ExerciseFactory` against the LIVE `ExerciseGenerator` for each one, not',
    ' * against a static literal (see this file\'s module doc for why: core-golden itself is stale',
    ' * for case.gen.neg, verified against the still-current TrainingParityTest).',
    ' */',
    'class UniversalCoreParityTest {',
    '    @Test fun everyExerciseFactoryCaseMatchesExerciseGeneratorByteForByte() {',
]
for c in ex['cases']:
    inp = c['input']
    draws = c['context']['randomDraws']
    draws_literal = 'listOf(%s)' % ', '.join(str(float(d)) for d in draws)
    lines.append('        run { // ' + c['id'])
    lines.append('            val draws = %s' % draws_literal)
    if 'step' in inp:
        step = inp['step'] - 1
        lines.append('            val legacy = legacyFactory(draws).generateChain(%s)[%d]' % (sentence_seed(inp['seed']), step))
        lines.append('            val steps = uc07ChainSteps(%s)' % s(inp['seed']['nounId']))
        lines.append('            val actual = uc07Generator(draws).generateChain(steps, %s)[%d].toLegacyExercise()' % (seed_map(inp['seed']), step))
    else:
        pref_legacy = 'null' if inp['preferred'] is None else sentence_seed(inp['preferred'])
        pref_new = 'null' if inp['preferred'] is None else seed_map(inp['preferred'])
        lines.append('            val legacy = legacyFactory(draws).generateForSkill(%s, %s)' % (s(inp['skillId']), pref_legacy))
        lines.append('            val actual = uc07Generator(draws).generateForSkill(%s, %s).toLegacyExercise()' % (s(inp['skillId']), pref_new))
    lines.append('            assertEquals(legacy, actual, %s)' % s(c['id']))
    lines.append('        }')
lines += ['    }', '}']
generated = '\n'.join(lines) + '\n'
OUT.write_text(generated)
print(f'{OUT}: {len(ex["cases"])} live-comparison cases from {FIXTURE}')
