package polski.core

import kotlin.test.Test
import kotlin.test.assertEquals
import polski.model.SentenceSeed

/**
 * Generated by generate_uc07_parity.py from tests/fixtures/core-golden/exercises.json's
 * (skillId/seed, RNG draws) inputs — DO NOT EDIT BY HAND. UniversalCorePlan.md §5.3/§12 UC-07:
 * compares the LIVE `ExerciseFactory` against the LIVE `ExerciseGenerator` for each one, not
 * against a static literal (see this file's module doc for why: core-golden itself is stale
 * for case.gen.neg, verified against the still-current TrainingParityTest).
 */
class UniversalCoreParityTest {
    @Test fun everyExerciseFactoryCaseMatchesExerciseGeneratorByteForByte() {
        run { // C-01-01
            val draws = listOf(0.11)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("wife", "beautiful"))[0]
            val steps = uc07ChainSteps("wife")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "wife", "adjective" to "beautiful"))[0].toLegacyExercise()
            assertEquals(legacy, actual, "C-01-01")
        }
        run { // C-01-02
            val draws = listOf(0.22)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("wife", "beautiful"))[1]
            val steps = uc07ChainSteps("wife")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "wife", "adjective" to "beautiful"))[1].toLegacyExercise()
            assertEquals(legacy, actual, "C-01-02")
        }
        run { // C-01-03
            val draws = listOf(0.33)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("wife", "beautiful"))[2]
            val steps = uc07ChainSteps("wife")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "wife", "adjective" to "beautiful"))[2].toLegacyExercise()
            assertEquals(legacy, actual, "C-01-03")
        }
        run { // C-01-04
            val draws = listOf(0.44)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("wife", "beautiful"))[3]
            val steps = uc07ChainSteps("wife")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "wife", "adjective" to "beautiful"))[3].toLegacyExercise()
            assertEquals(legacy, actual, "C-01-04")
        }
        run { // C-01-05
            val draws = listOf(0.55)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("wife", "beautiful"))[4]
            val steps = uc07ChainSteps("wife")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "wife", "adjective" to "beautiful"))[4].toLegacyExercise()
            assertEquals(legacy, actual, "C-01-05")
        }
        run { // C-02-01
            val draws = listOf(0.11)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("husband", "good"))[0]
            val steps = uc07ChainSteps("husband")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "husband", "adjective" to "good"))[0].toLegacyExercise()
            assertEquals(legacy, actual, "C-02-01")
        }
        run { // C-02-02
            val draws = listOf(0.22)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("husband", "good"))[1]
            val steps = uc07ChainSteps("husband")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "husband", "adjective" to "good"))[1].toLegacyExercise()
            assertEquals(legacy, actual, "C-02-02")
        }
        run { // C-02-03
            val draws = listOf(0.33)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("husband", "good"))[2]
            val steps = uc07ChainSteps("husband")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "husband", "adjective" to "good"))[2].toLegacyExercise()
            assertEquals(legacy, actual, "C-02-03")
        }
        run { // C-02-04
            val draws = listOf(0.44)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("husband", "good"))[3]
            val steps = uc07ChainSteps("husband")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "husband", "adjective" to "good"))[3].toLegacyExercise()
            assertEquals(legacy, actual, "C-02-04")
        }
        run { // C-02-05
            val draws = listOf(0.55)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("husband", "good"))[4]
            val steps = uc07ChainSteps("husband")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "husband", "adjective" to "good"))[4].toLegacyExercise()
            assertEquals(legacy, actual, "C-02-05")
        }
        run { // C-03-01
            val draws = listOf(0.11)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("friendM", "good"))[0]
            val steps = uc07ChainSteps("friendM")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "friendM", "adjective" to "good"))[0].toLegacyExercise()
            assertEquals(legacy, actual, "C-03-01")
        }
        run { // C-03-02
            val draws = listOf(0.22)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("friendM", "good"))[1]
            val steps = uc07ChainSteps("friendM")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "friendM", "adjective" to "good"))[1].toLegacyExercise()
            assertEquals(legacy, actual, "C-03-02")
        }
        run { // C-03-03
            val draws = listOf(0.33)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("friendM", "good"))[2]
            val steps = uc07ChainSteps("friendM")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "friendM", "adjective" to "good"))[2].toLegacyExercise()
            assertEquals(legacy, actual, "C-03-03")
        }
        run { // C-03-04
            val draws = listOf(0.44)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("friendM", "good"))[3]
            val steps = uc07ChainSteps("friendM")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "friendM", "adjective" to "good"))[3].toLegacyExercise()
            assertEquals(legacy, actual, "C-03-04")
        }
        run { // C-03-05
            val draws = listOf(0.55)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("friendM", "good"))[4]
            val steps = uc07ChainSteps("friendM")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "friendM", "adjective" to "good"))[4].toLegacyExercise()
            assertEquals(legacy, actual, "C-03-05")
        }
        run { // C-04-01
            val draws = listOf(0.11)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("son", "small"))[0]
            val steps = uc07ChainSteps("son")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "son", "adjective" to "small"))[0].toLegacyExercise()
            assertEquals(legacy, actual, "C-04-01")
        }
        run { // C-04-02
            val draws = listOf(0.22)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("son", "small"))[1]
            val steps = uc07ChainSteps("son")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "son", "adjective" to "small"))[1].toLegacyExercise()
            assertEquals(legacy, actual, "C-04-02")
        }
        run { // C-04-03
            val draws = listOf(0.33)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("son", "small"))[2]
            val steps = uc07ChainSteps("son")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "son", "adjective" to "small"))[2].toLegacyExercise()
            assertEquals(legacy, actual, "C-04-03")
        }
        run { // C-04-04
            val draws = listOf(0.44)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("son", "small"))[3]
            val steps = uc07ChainSteps("son")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "son", "adjective" to "small"))[3].toLegacyExercise()
            assertEquals(legacy, actual, "C-04-04")
        }
        run { // C-04-05
            val draws = listOf(0.55)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("son", "small"))[4]
            val steps = uc07ChainSteps("son")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "son", "adjective" to "small"))[4].toLegacyExercise()
            assertEquals(legacy, actual, "C-04-05")
        }
        run { // C-05-01
            val draws = listOf(0.11)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("dog", "good"))[0]
            val steps = uc07ChainSteps("dog")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "dog", "adjective" to "good"))[0].toLegacyExercise()
            assertEquals(legacy, actual, "C-05-01")
        }
        run { // C-05-02
            val draws = listOf(0.22)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("dog", "good"))[1]
            val steps = uc07ChainSteps("dog")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "dog", "adjective" to "good"))[1].toLegacyExercise()
            assertEquals(legacy, actual, "C-05-02")
        }
        run { // C-05-03
            val draws = listOf(0.33)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("dog", "good"))[2]
            val steps = uc07ChainSteps("dog")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "dog", "adjective" to "good"))[2].toLegacyExercise()
            assertEquals(legacy, actual, "C-05-03")
        }
        run { // C-05-04
            val draws = listOf(0.44)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("dog", "good"))[3]
            val steps = uc07ChainSteps("dog")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "dog", "adjective" to "good"))[3].toLegacyExercise()
            assertEquals(legacy, actual, "C-05-04")
        }
        run { // C-05-05
            val draws = listOf(0.55)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("dog", "good"))[4]
            val steps = uc07ChainSteps("dog")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "dog", "adjective" to "good"))[4].toLegacyExercise()
            assertEquals(legacy, actual, "C-05-05")
        }
        run { // C-06-01
            val draws = listOf(0.11)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("cat", "small"))[0]
            val steps = uc07ChainSteps("cat")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "cat", "adjective" to "small"))[0].toLegacyExercise()
            assertEquals(legacy, actual, "C-06-01")
        }
        run { // C-06-02
            val draws = listOf(0.22)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("cat", "small"))[1]
            val steps = uc07ChainSteps("cat")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "cat", "adjective" to "small"))[1].toLegacyExercise()
            assertEquals(legacy, actual, "C-06-02")
        }
        run { // C-06-03
            val draws = listOf(0.33)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("cat", "small"))[2]
            val steps = uc07ChainSteps("cat")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "cat", "adjective" to "small"))[2].toLegacyExercise()
            assertEquals(legacy, actual, "C-06-03")
        }
        run { // C-06-04
            val draws = listOf(0.44)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("cat", "small"))[3]
            val steps = uc07ChainSteps("cat")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "cat", "adjective" to "small"))[3].toLegacyExercise()
            assertEquals(legacy, actual, "C-06-04")
        }
        run { // C-06-05
            val draws = listOf(0.55)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("cat", "small"))[4]
            val steps = uc07ChainSteps("cat")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "cat", "adjective" to "small"))[4].toLegacyExercise()
            assertEquals(legacy, actual, "C-06-05")
        }
        run { // C-07-01
            val draws = listOf(0.11)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("book", "new"))[0]
            val steps = uc07ChainSteps("book")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "book", "adjective" to "new"))[0].toLegacyExercise()
            assertEquals(legacy, actual, "C-07-01")
        }
        run { // C-07-02
            val draws = listOf(0.22)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("book", "new"))[1]
            val steps = uc07ChainSteps("book")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "book", "adjective" to "new"))[1].toLegacyExercise()
            assertEquals(legacy, actual, "C-07-02")
        }
        run { // C-07-03
            val draws = listOf(0.33)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("book", "new"))[2]
            val steps = uc07ChainSteps("book")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "book", "adjective" to "new"))[2].toLegacyExercise()
            assertEquals(legacy, actual, "C-07-03")
        }
        run { // C-07-04
            val draws = listOf(0.44)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("book", "new"))[3]
            val steps = uc07ChainSteps("book")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "book", "adjective" to "new"))[3].toLegacyExercise()
            assertEquals(legacy, actual, "C-07-04")
        }
        run { // C-07-05
            val draws = listOf(0.55)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("book", "new"))[4]
            val steps = uc07ChainSteps("book")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "book", "adjective" to "new"))[4].toLegacyExercise()
            assertEquals(legacy, actual, "C-07-05")
        }
        run { // C-08-01
            val draws = listOf(0.11)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("car", "new"))[0]
            val steps = uc07ChainSteps("car")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "car", "adjective" to "new"))[0].toLegacyExercise()
            assertEquals(legacy, actual, "C-08-01")
        }
        run { // C-08-02
            val draws = listOf(0.22)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("car", "new"))[1]
            val steps = uc07ChainSteps("car")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "car", "adjective" to "new"))[1].toLegacyExercise()
            assertEquals(legacy, actual, "C-08-02")
        }
        run { // C-08-03
            val draws = listOf(0.33)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("car", "new"))[2]
            val steps = uc07ChainSteps("car")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "car", "adjective" to "new"))[2].toLegacyExercise()
            assertEquals(legacy, actual, "C-08-03")
        }
        run { // C-08-04
            val draws = listOf(0.44)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("car", "new"))[3]
            val steps = uc07ChainSteps("car")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "car", "adjective" to "new"))[3].toLegacyExercise()
            assertEquals(legacy, actual, "C-08-04")
        }
        run { // C-08-05
            val draws = listOf(0.55)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("car", "new"))[4]
            val steps = uc07ChainSteps("car")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "car", "adjective" to "new"))[4].toLegacyExercise()
            assertEquals(legacy, actual, "C-08-05")
        }
        run { // C-09-01
            val draws = listOf(0.11)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("house", "new"))[0]
            val steps = uc07ChainSteps("house")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "house", "adjective" to "new"))[0].toLegacyExercise()
            assertEquals(legacy, actual, "C-09-01")
        }
        run { // C-09-02
            val draws = listOf(0.22)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("house", "new"))[1]
            val steps = uc07ChainSteps("house")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "house", "adjective" to "new"))[1].toLegacyExercise()
            assertEquals(legacy, actual, "C-09-02")
        }
        run { // C-09-03
            val draws = listOf(0.33)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("house", "new"))[2]
            val steps = uc07ChainSteps("house")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "house", "adjective" to "new"))[2].toLegacyExercise()
            assertEquals(legacy, actual, "C-09-03")
        }
        run { // C-09-04
            val draws = listOf(0.44)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("house", "new"))[3]
            val steps = uc07ChainSteps("house")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "house", "adjective" to "new"))[3].toLegacyExercise()
            assertEquals(legacy, actual, "C-09-04")
        }
        run { // C-09-05
            val draws = listOf(0.55)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("house", "new"))[4]
            val steps = uc07ChainSteps("house")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "house", "adjective" to "new"))[4].toLegacyExercise()
            assertEquals(legacy, actual, "C-09-05")
        }
        run { // C-10-01
            val draws = listOf(0.11)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("phone", "new"))[0]
            val steps = uc07ChainSteps("phone")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "phone", "adjective" to "new"))[0].toLegacyExercise()
            assertEquals(legacy, actual, "C-10-01")
        }
        run { // C-10-02
            val draws = listOf(0.22)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("phone", "new"))[1]
            val steps = uc07ChainSteps("phone")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "phone", "adjective" to "new"))[1].toLegacyExercise()
            assertEquals(legacy, actual, "C-10-02")
        }
        run { // C-10-03
            val draws = listOf(0.33)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("phone", "new"))[2]
            val steps = uc07ChainSteps("phone")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "phone", "adjective" to "new"))[2].toLegacyExercise()
            assertEquals(legacy, actual, "C-10-03")
        }
        run { // C-10-04
            val draws = listOf(0.44)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("phone", "new"))[3]
            val steps = uc07ChainSteps("phone")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "phone", "adjective" to "new"))[3].toLegacyExercise()
            assertEquals(legacy, actual, "C-10-04")
        }
        run { // C-10-05
            val draws = listOf(0.55)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("phone", "new"))[4]
            val steps = uc07ChainSteps("phone")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "phone", "adjective" to "new"))[4].toLegacyExercise()
            assertEquals(legacy, actual, "C-10-05")
        }
        run { // C-11-01
            val draws = listOf(0.11)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("child", "small"))[0]
            val steps = uc07ChainSteps("child")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "child", "adjective" to "small"))[0].toLegacyExercise()
            assertEquals(legacy, actual, "C-11-01")
        }
        run { // C-11-02
            val draws = listOf(0.22)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("child", "small"))[1]
            val steps = uc07ChainSteps("child")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "child", "adjective" to "small"))[1].toLegacyExercise()
            assertEquals(legacy, actual, "C-11-02")
        }
        run { // C-11-03
            val draws = listOf(0.33)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("child", "small"))[2]
            val steps = uc07ChainSteps("child")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "child", "adjective" to "small"))[2].toLegacyExercise()
            assertEquals(legacy, actual, "C-11-03")
        }
        run { // C-11-04
            val draws = listOf(0.44)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("child", "small"))[3]
            val steps = uc07ChainSteps("child")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "child", "adjective" to "small"))[3].toLegacyExercise()
            assertEquals(legacy, actual, "C-11-04")
        }
        run { // C-11-05
            val draws = listOf(0.55)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("child", "small"))[4]
            val steps = uc07ChainSteps("child")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "child", "adjective" to "small"))[4].toLegacyExercise()
            assertEquals(legacy, actual, "C-11-05")
        }
        run { // C-12-01
            val draws = listOf(0.11)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("window", "new"))[0]
            val steps = uc07ChainSteps("window")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "window", "adjective" to "new"))[0].toLegacyExercise()
            assertEquals(legacy, actual, "C-12-01")
        }
        run { // C-12-02
            val draws = listOf(0.22)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("window", "new"))[1]
            val steps = uc07ChainSteps("window")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "window", "adjective" to "new"))[1].toLegacyExercise()
            assertEquals(legacy, actual, "C-12-02")
        }
        run { // C-12-03
            val draws = listOf(0.33)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("window", "new"))[2]
            val steps = uc07ChainSteps("window")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "window", "adjective" to "new"))[2].toLegacyExercise()
            assertEquals(legacy, actual, "C-12-03")
        }
        run { // C-12-04
            val draws = listOf(0.44)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("window", "new"))[3]
            val steps = uc07ChainSteps("window")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "window", "adjective" to "new"))[3].toLegacyExercise()
            assertEquals(legacy, actual, "C-12-04")
        }
        run { // C-12-05
            val draws = listOf(0.55)
            val legacy = legacyFactory(draws).generateChain(SentenceSeed("window", "new"))[4]
            val steps = uc07ChainSteps("window")
            val actual = uc07Generator(draws).generateChain(steps, mapOf("noun" to "window", "adjective" to "new"))[4].toLegacyExercise()
            assertEquals(legacy, actual, "C-12-05")
        }
        run { // E-case.acc.n-preferred
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.acc.n", SentenceSeed("wife", "beautiful"))
            val actual = uc07Generator(draws).generateForSkill("case.acc.n", mapOf("noun" to "wife", "adjective" to "beautiful")).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.acc.n-preferred")
        }
        run { // E-case.acc.n-fallback
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.acc.n", SentenceSeed("window", "new"))
            val actual = uc07Generator(draws).generateForSkill("case.acc.n", mapOf("noun" to "window", "adjective" to "new")).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.acc.n-fallback")
        }
        run { // E-case.acc.n-random
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.acc.n", null)
            val actual = uc07Generator(draws).generateForSkill("case.acc.n", null).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.acc.n-random")
        }
        run { // E-case.acc.f-preferred
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.acc.f", SentenceSeed("wife", "beautiful"))
            val actual = uc07Generator(draws).generateForSkill("case.acc.f", mapOf("noun" to "wife", "adjective" to "beautiful")).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.acc.f-preferred")
        }
        run { // E-case.acc.f-fallback
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.acc.f", SentenceSeed("window", "new"))
            val actual = uc07Generator(draws).generateForSkill("case.acc.f", mapOf("noun" to "window", "adjective" to "new")).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.acc.f-fallback")
        }
        run { // E-case.acc.f-random
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.acc.f", null)
            val actual = uc07Generator(draws).generateForSkill("case.acc.f", null).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.acc.f-random")
        }
        run { // E-case.acc.m-preferred
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.acc.m", SentenceSeed("wife", "beautiful"))
            val actual = uc07Generator(draws).generateForSkill("case.acc.m", mapOf("noun" to "wife", "adjective" to "beautiful")).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.acc.m-preferred")
        }
        run { // E-case.acc.m-fallback
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.acc.m", SentenceSeed("window", "new"))
            val actual = uc07Generator(draws).generateForSkill("case.acc.m", mapOf("noun" to "window", "adjective" to "new")).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.acc.m-fallback")
        }
        run { // E-case.acc.m-random
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.acc.m", null)
            val actual = uc07Generator(draws).generateForSkill("case.acc.m", null).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.acc.m-random")
        }
        run { // E-case.gen.neg-preferred
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.gen.neg", SentenceSeed("wife", "beautiful"))
            val actual = uc07Generator(draws).generateForSkill("case.gen.neg", mapOf("noun" to "wife", "adjective" to "beautiful")).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.gen.neg-preferred")
        }
        run { // E-case.gen.neg-fallback
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.gen.neg", SentenceSeed("window", "new"))
            val actual = uc07Generator(draws).generateForSkill("case.gen.neg", mapOf("noun" to "window", "adjective" to "new")).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.gen.neg-fallback")
        }
        run { // E-case.gen.neg-random
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.gen.neg", null)
            val actual = uc07Generator(draws).generateForSkill("case.gen.neg", null).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.gen.neg-random")
        }
        run { // E-case.inst-preferred
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.inst", SentenceSeed("wife", "beautiful"))
            val actual = uc07Generator(draws).generateForSkill("case.inst", mapOf("noun" to "wife", "adjective" to "beautiful")).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.inst-preferred")
        }
        run { // E-case.inst-fallback
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.inst", SentenceSeed("window", "new"))
            val actual = uc07Generator(draws).generateForSkill("case.inst", mapOf("noun" to "window", "adjective" to "new")).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.inst-fallback")
        }
        run { // E-case.inst-random
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.inst", null)
            val actual = uc07Generator(draws).generateForSkill("case.inst", null).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.inst-random")
        }
        run { // E-case.loc-preferred
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.loc", SentenceSeed("wife", "beautiful"))
            val actual = uc07Generator(draws).generateForSkill("case.loc", mapOf("noun" to "wife", "adjective" to "beautiful")).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.loc-preferred")
        }
        run { // E-case.loc-fallback
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.loc", SentenceSeed("window", "new"))
            val actual = uc07Generator(draws).generateForSkill("case.loc", mapOf("noun" to "window", "adjective" to "new")).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.loc-fallback")
        }
        run { // E-case.loc-random
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.loc", null)
            val actual = uc07Generator(draws).generateForSkill("case.loc", null).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.loc-random")
        }
        run { // E-case.dat-preferred
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.dat", SentenceSeed("wife", "beautiful"))
            val actual = uc07Generator(draws).generateForSkill("case.dat", mapOf("noun" to "wife", "adjective" to "beautiful")).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.dat-preferred")
        }
        run { // E-case.dat-fallback
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.dat", SentenceSeed("window", "new"))
            val actual = uc07Generator(draws).generateForSkill("case.dat", mapOf("noun" to "window", "adjective" to "new")).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.dat-fallback")
        }
        run { // E-case.dat-random
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("case.dat", null)
            val actual = uc07Generator(draws).generateForSkill("case.dat", null).toLegacyExercise()
            assertEquals(legacy, actual, "E-case.dat-random")
        }
        run { // E-agreement.my-preferred
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("agreement.my", SentenceSeed("wife", "beautiful"))
            val actual = uc07Generator(draws).generateForSkill("agreement.my", mapOf("noun" to "wife", "adjective" to "beautiful")).toLegacyExercise()
            assertEquals(legacy, actual, "E-agreement.my-preferred")
        }
        run { // E-agreement.my-fallback
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("agreement.my", SentenceSeed("window", "new"))
            val actual = uc07Generator(draws).generateForSkill("agreement.my", mapOf("noun" to "window", "adjective" to "new")).toLegacyExercise()
            assertEquals(legacy, actual, "E-agreement.my-fallback")
        }
        run { // E-agreement.my-random
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("agreement.my", null)
            val actual = uc07Generator(draws).generateForSkill("agreement.my", null).toLegacyExercise()
            assertEquals(legacy, actual, "E-agreement.my-random")
        }
        run { // E-verb.present-preferred
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("verb.present", SentenceSeed("wife", "beautiful"))
            val actual = uc07Generator(draws).generateForSkill("verb.present", mapOf("noun" to "wife", "adjective" to "beautiful")).toLegacyExercise()
            assertEquals(legacy, actual, "E-verb.present-preferred")
        }
        run { // E-verb.present-fallback
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("verb.present", SentenceSeed("window", "new"))
            val actual = uc07Generator(draws).generateForSkill("verb.present", mapOf("noun" to "window", "adjective" to "new")).toLegacyExercise()
            assertEquals(legacy, actual, "E-verb.present-fallback")
        }
        run { // E-verb.present-random
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("verb.present", null)
            val actual = uc07Generator(draws).generateForSkill("verb.present", null).toLegacyExercise()
            assertEquals(legacy, actual, "E-verb.present-random")
        }
        run { // E-verb.past-preferred
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("verb.past", SentenceSeed("wife", "beautiful"))
            val actual = uc07Generator(draws).generateForSkill("verb.past", mapOf("noun" to "wife", "adjective" to "beautiful")).toLegacyExercise()
            assertEquals(legacy, actual, "E-verb.past-preferred")
        }
        run { // E-verb.past-fallback
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("verb.past", SentenceSeed("window", "new"))
            val actual = uc07Generator(draws).generateForSkill("verb.past", mapOf("noun" to "window", "adjective" to "new")).toLegacyExercise()
            assertEquals(legacy, actual, "E-verb.past-fallback")
        }
        run { // E-verb.past-random
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("verb.past", null)
            val actual = uc07Generator(draws).generateForSkill("verb.past", null).toLegacyExercise()
            assertEquals(legacy, actual, "E-verb.past-random")
        }
        run { // E-verb.future-preferred
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("verb.future", SentenceSeed("wife", "beautiful"))
            val actual = uc07Generator(draws).generateForSkill("verb.future", mapOf("noun" to "wife", "adjective" to "beautiful")).toLegacyExercise()
            assertEquals(legacy, actual, "E-verb.future-preferred")
        }
        run { // E-verb.future-fallback
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("verb.future", SentenceSeed("window", "new"))
            val actual = uc07Generator(draws).generateForSkill("verb.future", mapOf("noun" to "window", "adjective" to "new")).toLegacyExercise()
            assertEquals(legacy, actual, "E-verb.future-fallback")
        }
        run { // E-verb.future-random
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("verb.future", null)
            val actual = uc07Generator(draws).generateForSkill("verb.future", null).toLegacyExercise()
            assertEquals(legacy, actual, "E-verb.future-random")
        }
        run { // E-aspect-preferred
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("aspect", SentenceSeed("wife", "beautiful"))
            val actual = uc07Generator(draws).generateForSkill("aspect", mapOf("noun" to "wife", "adjective" to "beautiful")).toLegacyExercise()
            assertEquals(legacy, actual, "E-aspect-preferred")
        }
        run { // E-aspect-fallback
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("aspect", SentenceSeed("window", "new"))
            val actual = uc07Generator(draws).generateForSkill("aspect", mapOf("noun" to "window", "adjective" to "new")).toLegacyExercise()
            assertEquals(legacy, actual, "E-aspect-fallback")
        }
        run { // E-aspect-random
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("aspect", null)
            val actual = uc07Generator(draws).generateForSkill("aspect", null).toLegacyExercise()
            assertEquals(legacy, actual, "E-aspect-random")
        }
        run { // E-pronouns-preferred
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("pronouns", SentenceSeed("wife", "beautiful"))
            val actual = uc07Generator(draws).generateForSkill("pronouns", mapOf("noun" to "wife", "adjective" to "beautiful")).toLegacyExercise()
            assertEquals(legacy, actual, "E-pronouns-preferred")
        }
        run { // E-pronouns-fallback
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("pronouns", SentenceSeed("window", "new"))
            val actual = uc07Generator(draws).generateForSkill("pronouns", mapOf("noun" to "window", "adjective" to "new")).toLegacyExercise()
            assertEquals(legacy, actual, "E-pronouns-fallback")
        }
        run { // E-pronouns-random
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("pronouns", null)
            val actual = uc07Generator(draws).generateForSkill("pronouns", null).toLegacyExercise()
            assertEquals(legacy, actual, "E-pronouns-random")
        }
        run { // E-mixed-preferred
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("mixed", SentenceSeed("wife", "beautiful"))
            val actual = uc07Generator(draws).generateForSkill("mixed", mapOf("noun" to "wife", "adjective" to "beautiful")).toLegacyExercise()
            assertEquals(legacy, actual, "E-mixed-preferred")
        }
        run { // E-mixed-fallback
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("mixed", SentenceSeed("window", "new"))
            val actual = uc07Generator(draws).generateForSkill("mixed", mapOf("noun" to "window", "adjective" to "new")).toLegacyExercise()
            assertEquals(legacy, actual, "E-mixed-fallback")
        }
        run { // E-mixed-random
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("mixed", null)
            val actual = uc07Generator(draws).generateForSkill("mixed", null).toLegacyExercise()
            assertEquals(legacy, actual, "E-mixed-random")
        }
        run { // E-sentence.question-preferred
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("sentence.question", SentenceSeed("wife", "beautiful"))
            val actual = uc07Generator(draws).generateForSkill("sentence.question", mapOf("noun" to "wife", "adjective" to "beautiful")).toLegacyExercise()
            assertEquals(legacy, actual, "E-sentence.question-preferred")
        }
        run { // E-sentence.question-fallback
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("sentence.question", SentenceSeed("window", "new"))
            val actual = uc07Generator(draws).generateForSkill("sentence.question", mapOf("noun" to "window", "adjective" to "new")).toLegacyExercise()
            assertEquals(legacy, actual, "E-sentence.question-fallback")
        }
        run { // E-sentence.question-random
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("sentence.question", null)
            val actual = uc07Generator(draws).generateForSkill("sentence.question", null).toLegacyExercise()
            assertEquals(legacy, actual, "E-sentence.question-random")
        }
        run { // E-sentence.plural-preferred
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("sentence.plural", SentenceSeed("wife", "beautiful"))
            val actual = uc07Generator(draws).generateForSkill("sentence.plural", mapOf("noun" to "wife", "adjective" to "beautiful")).toLegacyExercise()
            assertEquals(legacy, actual, "E-sentence.plural-preferred")
        }
        run { // E-sentence.plural-fallback
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("sentence.plural", SentenceSeed("window", "new"))
            val actual = uc07Generator(draws).generateForSkill("sentence.plural", mapOf("noun" to "window", "adjective" to "new")).toLegacyExercise()
            assertEquals(legacy, actual, "E-sentence.plural-fallback")
        }
        run { // E-sentence.plural-random
            val draws = listOf(0.34, 0.72, 0.18)
            val legacy = legacyFactory(draws).generateForSkill("sentence.plural", null)
            val actual = uc07Generator(draws).generateForSkill("sentence.plural", null).toLegacyExercise()
            assertEquals(legacy, actual, "E-sentence.plural-random")
        }
        run { // E-agreement.my-accepted
            val draws = listOf(0.2, 0.4, 0.6)
            val legacy = legacyFactory(draws).generateForSkill("agreement.my", SentenceSeed("wife", "beautiful"))
            val actual = uc07Generator(draws).generateForSkill("agreement.my", mapOf("noun" to "wife", "adjective" to "beautiful")).toLegacyExercise()
            assertEquals(legacy, actual, "E-agreement.my-accepted")
        }
        run { // E-verb.future-accepted
            val draws = listOf(0.2, 0.4, 0.6)
            val legacy = legacyFactory(draws).generateForSkill("verb.future", SentenceSeed("husband", "good"))
            val actual = uc07Generator(draws).generateForSkill("verb.future", mapOf("noun" to "husband", "adjective" to "good")).toLegacyExercise()
            assertEquals(legacy, actual, "E-verb.future-accepted")
        }
        run { // E-aspect-accepted
            val draws = listOf(0.2, 0.4, 0.6)
            val legacy = legacyFactory(draws).generateForSkill("aspect", SentenceSeed("book", "new"))
            val actual = uc07Generator(draws).generateForSkill("aspect", mapOf("noun" to "book", "adjective" to "new")).toLegacyExercise()
            assertEquals(legacy, actual, "E-aspect-accepted")
        }
        run { // E-mixed-accepted
            val draws = listOf(0.2, 0.4, 0.6)
            val legacy = legacyFactory(draws).generateForSkill("mixed", SentenceSeed("wife", "beautiful"))
            val actual = uc07Generator(draws).generateForSkill("mixed", mapOf("noun" to "wife", "adjective" to "beautiful")).toLegacyExercise()
            assertEquals(legacy, actual, "E-mixed-accepted")
        }
    }
}
