import type { Exercise,Gender,NumberGram,Person,Tense } from '../types';import {nouns} from '../data/nouns';import {adjectives} from '../data/adjectives';import {personalPronouns} from '../data/pronouns';import {verbs,verbById} from '../data/verbs';import {capitalize,nounPhrase,verbForm} from '../grammar/engine';
const pick=<T,>(a:T[]):T=>a[Math.floor(Math.random()*a.length)];const eid=()=>Math.random().toString(36).slice(2);
const objNouns=()=>nouns.filter(n=>!['child'].includes(n.id));
const subjects=[{label:'JA',p:1 as Person,n:'sg' as NumberGram,g:'m-personal' as Gender},{label:'TY',p:2 as Person,n:'sg' as NumberGram,g:'m-personal' as Gender},{label:'ONA',p:3 as Person,n:'sg' as NumberGram,g:'f' as Gender},{label:'MY',p:1 as Person,n:'pl' as NumberGram,g:'m-personal' as Gender},{label:'ONI',p:3 as Person,n:'pl' as NumberGram,g:'m-personal' as Gender}];
export function generateForSkill(skillId:string):Exercise{
 const noun=pick(objNouns()),adj=pick(adjectives), id=eid();
 if(skillId==='case.acc.f'){const n=pick(nouns.filter(x=>x.gender==='f'));return {id,primarySkill:skillId,prompt:`Widzę + ${adj.lemma} ${n.lemma} → ?`,expected:`Widzę ${nounPhrase(n.id,'acc',{adjectiveId:adj.id})}.`,explanation:`Biernik: ${adj.lemma} ${n.lemma} → ${nounPhrase(n.id,'acc',{adjectiveId:adj.id})}.`,tags:['acc','f']}}
 if(skillId==='case.acc.m'){const n=pick(nouns.filter(x=>x.gender.startsWith('m-')));return {id,primarySkill:skillId,prompt:`Widzę + ${adj.lemma} ${n.lemma} → ?`,expected:`Widzę ${nounPhrase(n.id,'acc',{adjectiveId:adj.id})}.`,explanation:n.gender==='m-inanimate'?'Nieżywotny: Biernik = Mianownik.':n.lemma.endsWith('a')?'Мужское существительное на -a: kolega → kolegę, но прилагательное как в Dopełniaczu.':'Żywotny/osobowy на согласную: Biernik = Dopełniacz.',tags:['acc','m']}}
 if(skillId==='case.gen.neg'){return {id,primarySkill:skillId,prompt:`NEGACJA: Mam ${nounPhrase(noun.id,'acc',{adjectiveId:adj.id})}.`,expected:`Nie mam ${nounPhrase(noun.id,'gen',{adjectiveId:adj.id})}.`,explanation:'Отрицание меняет объект на Dopełniacz.',tags:['gen','neg']}}
 if(skillId==='case.inst'){return {id,primarySkill:skillId,prompt:`Idę z + ${adj.lemma} ${noun.lemma} → ?`,expected:`Idę z ${nounPhrase(noun.id,'inst',{adjectiveId:adj.id})}.`,explanation:'z (с кем/чем) требует Narzędnik.',tags:['inst']}}
 if(skillId==='case.loc'){return {id,primarySkill:skillId,prompt:`Mówię o + ${adj.lemma} ${noun.lemma} → ?`,expected:`Mówię o ${nounPhrase(noun.id,'loc',{adjectiveId:adj.id})}.`,explanation:'o + Miejscownik.',tags:['loc']}}
 if(skillId==='case.dat'){const n=pick(nouns.filter(x=>x.gender==='f'||x.gender==='m-personal'));return {id,primarySkill:skillId,prompt:`Daję prezent + ${n.lemma} → ?`,expected:`Daję prezent ${nounPhrase(n.id,'dat')}.`,explanation:'Получатель стоит в Celowniku.',tags:['dat']}}
 if(skillId==='agreement.my'){const c=pick(['acc','gen','inst','loc'] as const);const prep=c==='acc'?'Widzę':c==='gen'?'Nie mam':c==='inst'?'Idę z':'Mówię o';return {id,primarySkill:skillId,prompt:`${prep}: MÓJ + ${adj.lemma} + ${noun.lemma}`,expected:`${prep} ${nounPhrase(noun.id,c,{adjectiveId:adj.id,possessive:true})}.`,explanation:`Все элементы согласуются: ${nounPhrase(noun.id,c,{adjectiveId:adj.id,possessive:true})}.`,tags:['agreement',c]}}
 if(skillId==='verb.present'||skillId==='verb.past'||skillId==='verb.future'){const s=pick(subjects), tense=(skillId.split('.')[1] as Tense),v=pick(verbs.filter(x=>x.aspect==='imperfective'&&x.id!=='be'));const subject=s.label==='ONA'?'Ona':s.label==='ONI'?'Oni':s.label==='MY'?'My':s.label==='TY'?'Ty':'Ja';return {id,primarySkill:skillId,prompt:`${s.label} + ${v.lemma} · ${tense.toUpperCase()}`,expected:`${subject} ${verbForm(v.id,tense,s.p,s.n,s.g)}.`,accepted:tense==='past'&&s.n==='sg'&&s.p!==3?[`${subject} ${verbForm(v.id,tense,s.p,s.n,'f')}.`]:[],explanation:`${v.lemma}: ${verbForm(v.id,tense,s.p,s.n,s.g)}`,tags:['verb',tense]}}
 if(skillId==='aspect'){const pair=pick(verbs.filter(v=>v.perfectivePair));const perf=verbById(pair.perfectivePair!);return {id,primarySkill:skillId,prompt:`Завершённый результат вчера: JA + ${pair.lemma} → dokonany`,expected:`Wczoraj ${verbForm(perf.id,'past',1,'sg','m-personal')}.`,accepted:[`Wczoraj ${verbForm(perf.id,'past',1,'sg','f')}.`],explanation:`Для завершённого результата: ${pair.lemma} → ${perf.lemma}.`,tags:['aspect']}}
 if(skillId==='pronouns'){const key=pick(['ona','on','oni'] as const),c=pick(['acc','inst','loc','dat'] as const),forms=personalPronouns[key],prefix=c==='acc'?'Widzę':c==='inst'?'Idę z':c==='loc'?'Mówię o':'Daję prezent';return {id,primarySkill:skillId,prompt:`${prefix} + ${key.toUpperCase()} → ?`,expected:`${prefix} ${forms[c]}.`,explanation:`${key} → ${forms[c]} (${c})`,tags:['pronoun',c]}}
 // mixed
 const n=pick(nouns.filter(x=>x.gender==='f'||x.gender==='m-inanimate'));return {id,primarySkill:'mixed',prompt:`TY · PAST · NEGACJA: widzieć + MÓJ + ${adj.lemma} + ${n.lemma}`,expected:`Nie widziałeś ${nounPhrase(n.id,'gen',{adjectiveId:adj.id,possessive:true})}.`,accepted:[`Nie widziałaś ${nounPhrase(n.id,'gen',{adjectiveId:adj.id,possessive:true})}.`],explanation:'Past + negation + Dopełniacz + agreement.',tags:['mixed']};
}
