import type { Skill } from '../types';
export const skills:Skill[]=[
{id:'case.acc.f',title:'Biernik · żeński',group:'Przypadki',level:'A1',formula:'-a → -ę; adjective -a → -ą',theory:'Прямой объект после widzę, mam, lubię, kupuję обычно стоит в Bierniku.',hint:'Widzę kogo? co?',prerequisites:[]},
{id:'case.acc.m',title:'Biernik · męski',group:'Przypadki',level:'A2',formula:'на согласную: живое = Gen; неживое = Nom',theory:'Для мужских существительных на согласную: widzę męża/psa, но widzę dom/samochód. У существительных на -a: widzę kolegę, но nie widzę kolegi.',hint:'Сначала определи: żywotny или nieżywotny.',prerequisites:['case.acc.f']},
{id:'case.gen.neg',title:'Dopełniacz · negacja',group:'Przypadki',level:'A2',formula:'Mam X → Nie mam + GEN',theory:'При отрицании прямого объекта Biernik очень часто превращается в Dopełniacz.',hint:'Не меняй только nie — поменяй весь noun phrase.',prerequisites:['case.acc.f']},
{id:'case.inst',title:'Narzędnik · z / być',group:'Przypadki',level:'A1',formula:'z + kim? czym? → INST',theory:'После z в значении «с кем/чем» используем Narzędnik. Также: Jestem programistą.',hint:'z moją żoną, z dobrym kolegą',prerequisites:[]},
{id:'case.loc',title:'Miejscownik · o',group:'Przypadki',level:'A2',formula:'o + kim? czym? → LOC',theory:'После o (о ком/о чём) нужен Miejscownik.',hint:'mówię o żonie / domu',prerequisites:['case.inst']},
{id:'case.dat',title:'Celownik · komu?',group:'Przypadki',level:'A2',formula:'daję/pomagam + DAT',theory:'Celownik отвечает «кому? чему?». Учим через короткие устойчивые конструкции.',hint:'Daję prezent komu?',prerequisites:[]},
{id:'agreement.my',title:'mój + adjective + noun',group:'Zgoda',level:'A2',formula:'Все 3 слова получают один case/gender/number',theory:'Не учим окончания отдельно: трансформируем целую группу mój + adjective + noun.',hint:'moja piękna żona → mojej pięknej żony',prerequisites:['case.acc.f','case.gen.neg']},
{id:'verb.present',title:'Czas teraźniejszy',group:'Czasownik',level:'A1',formula:'person × number → końcówka',theory:'Автоматизируем 6 лиц на высокочастотных глаголах.',hint:'ja/ty/on/my/wy/oni',prerequisites:[]},
{id:'verb.past',title:'Czas przeszły',group:'Czasownik',level:'A2',formula:'past stem + gender + person',theory:'В прошедшем времени форма отражает род говорящего/подлежащего и лицо.',hint:'robił-em, robiła-m, robili-śmy',prerequisites:['verb.present']},
{id:'verb.future',title:'Czas przyszły',group:'Czasownik',level:'A2',formula:'będę + infinitive (imperf.) / present-form (perf.)',theory:'Для несовершенного вида: będę robić. Совершенный вид имеет простое будущее: zrobię.',hint:'będę czytać / kupię',prerequisites:['verb.present']},
{id:'aspect',title:'Aspekt · robić/zrobić',group:'Czasownik',level:'B1',formula:'process/repetition ↔ completed result',theory:'Недоконанный вид описывает процесс/повторяемость, dokonany — завершённый результат.',hint:'robiłem vs zrobiłem',prerequisites:['verb.past','verb.future']},
{id:'pronouns',title:'Zaimki osobowe',group:'Zaimki',level:'A2',formula:'ona → ją / jej / nią / niej',theory:'Тренируем местоимение сразу внутри конструкции, а не как отдельную таблицу.',hint:'widzę ją; mówię o niej; idę z nią',prerequisites:['case.inst','case.loc']},
{id:'mixed',title:'Mixed transformations',group:'B1 Core',level:'B1',formula:'tense + negation + case + agreement',theory:'Смешанные карточки проверяют, можешь ли ты объединить правила в живом предложении.',hint:'Сначала структура, затем окончания.',prerequisites:['agreement.my','verb.past']}
];
export const skillById=(id:string)=>{const s=skills.find(x=>x.id===id);if(!s)throw new Error(`Unknown skill ${id}`);return s};
