"""Regenerate Kotlin oracle assertions from pinned React scheduler fixture.

Source: tests/fixtures/kotlin-parity/scheduler.json, generated against ts-fsrs 5.4.2.
Run from repository root: python3 kotlin/shared/src/commonTest/kotlin/polski/srs/generate_parity.py
"""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[7]
fixture = json.loads((root / "tests/fixtures/kotlin-parity/scheduler.json").read_text())
out = Path(__file__).with_name("SchedulerOracleTest.kt")

def q(s): return json.dumps(s, ensure_ascii=False)
def serialized(c):
    last = q(c["last_review"]) if c.get("last_review") else "null"
    return f'SerializedCard({q(c["due"])}, {float(c["stability"])}, {float(c["difficulty"])}, {c["elapsed_days"]}, {c["scheduled_days"]}, {c["reps"]}, {c["lapses"]}, {c["learning_steps"]}, {c["state"]}, {last})'

def card(c):
    return f'SrsCard(Instant.parse({q(c["due"])}), {float(c["stability"])} , {float(c["difficulty"])} , {c["elapsed_days"]}, {c["scheduled_days"]}, {c["reps"]}, {c["lapses"]}, {c["learning_steps"]}, CardState.entries[{c["state"]}], ' + (f'Instant.parse({q(c["last_review"])})' if c.get('last_review') else 'null') + ')'

lines = ["package polski.srs", "", "import kotlin.test.Test", "import kotlin.test.assertEquals", "import kotlin.test.assertTrue", "import kotlin.math.abs", "import kotlin.time.Instant", "", "/** Generated by generate_parity.py from the pinned 21-case ts-fsrs 5.4.2 oracle. */", "class SchedulerOracleTest {", "    private val scheduler = FsrsScheduler()", "    private fun assertCard(expected: SrsCard, actual: SrsCard, id: String) {", "        assertEquals(expected.due, actual.due, id + \" due\")", "        assertTrue(abs(expected.stability - actual.stability) <= 1e-7, id + \" stability: \" + actual.stability)", "        assertTrue(abs(expected.difficulty - actual.difficulty) <= 1e-7, id + \" difficulty: \" + actual.difficulty)", "        assertEquals(expected.elapsedDays, actual.elapsedDays, id + \" elapsed\")", "        assertEquals(expected.scheduledDays, actual.scheduledDays, id + \" scheduled\")", "        assertEquals(expected.reps, actual.reps, id + \" reps\")", "        assertEquals(expected.lapses, actual.lapses, id + \" lapses\")", "        assertEquals(expected.learningSteps, actual.learningSteps, id + \" steps\")", "        assertEquals(expected.state, actual.state, id + \" state\")", "        assertEquals(expected.lastReview, actual.lastReview, id + \" last review\")", "    }", ""]
for x in fixture['cases']:
    name = x['id'].replace('-', '_')
    input = x['input']; expected=x['expected']; original=input['card']; at=x['context']['nowIso']
    lines += [f'    @Test fun {name}() {{', f'        val at = Instant.parse({q(at)})', f'        val source = StoredCard({q(original["skillId"])}, {card(original["card"])})', '        val before = source.copy(card = source.card.copy())', f'        assertEquals({serialized(expected.get("roundTrip", original["card"]))}, SrsCardWire.encode(source.card), {q(x["id"] + " roundTrip")})', '        val preview = scheduler.preview(source, at)']
    for rating in ['again','hard','good','easy']:
        lines += [f'        assertEquals(Instant.parse({q(expected["preview"][rating])}), preview.{rating}, {q(x["id"] + " preview " + rating)})']
    lines += [f'        val reviewed = scheduler.review(source, Rating.{input["rating"].title()}, at)', f'        assertEquals({q(expected["review"]["skillId"])}, reviewed.skillId)', f'        assertCard({card(expected["review"]["card"])}, reviewed.card, {q(x["id"])})', f'        assertEquals({str(expected["due"]).lower()}, scheduler.isDue(source, at))', '        assertEquals(before, source)', '        assertEquals(preview[Rating.'+input['rating'].title()+'], reviewed.card.due)', '    }', '']
lines += ['}']
out.write_text('\n'.join(lines)+'\n')
print(f'Wrote {out} with {len(fixture["cases"])} cases')
